### ISSUE TITLE
Installer error: Customized functionality in this application will not work

### ISSUE THREAD

**Issue by greinerk** [ben-spiller/OutlookBetterReminders#2]
Installing on Windows 10 running Office 365 and received the following error when attempting to install:

Customized functionality in this application will not work because the certificate used to sign the deployment manifest for Outlook BetterReminders or its location is not trusted. Contact your administrator for further assistance.

After following the directions this link: https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-configure-inclusion-list-security?redirectedfrom=MSDN&view=vs-2019
I was able to install successfully using these values:

Internet = AuthenticodeRequired
UntrustedSites = Disabled
MyComputer = Enabled
LocalIntranet = Disabled
TrustedSites = Enabled

This seems prohibitive for many users. Can this be simplified?

**Comment by ben-spiller** [comment]
Hi I've been looking into this... I'd love to solve it but unfortunately there is no such thing as a free provider of certificates for code signing purposes (only for https, which is not what we need here) so I'd have to personally pay at least $70 per year to get a trusted certificate which isn't practical for something free like this. 

So I believe the only options are to tweak the security settings as you suggest above, or if you're lucky enough to have a certificate (and access to the private key) to making a custom build of this add-on with your certificate.
