### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by softmade-timobruentjen** [ben-spiller/OutlookBetterReminders#3]
Very useful!
I´ve added a regex append for german meetings:
(Join .*[Mm]eeting <(?<url>[^>]+)>|An .*[Bb]esprechung teilnehmen <(?<url>[^>]+)>)

Please add some documentation to this, for someone who isn´t firm with the code and just uses the addin.

Thanks in advance for your coding efforts! It saves a lot of time for opening meeting links

**Comment by ben-spiller** [comment]
Thanks. I've it a little more obvious that the Options dialog is how you deal with translation/language issues, and also will be releasing a new version that does a slightly better job at recognizing common URLs (for MS Teams/Zoom) without caring about the language. Of course you do need to know how regex's work to use this feature but it's a bit hard to get around that.
