### ISSUE TITLE
Suggestion to http(s) post on event

### ISSUE THREAD

**Issue by jkister** [ben-spiller/OutlookBetterReminders#6]
Thank you for this code, just found it and it's perfect.

Feature request:  send a post to a specified url that includes the subject/time/etc whenever a reminder is triggered (whenever the popup window appears?).

Use case: have a script on my webserver (or even just an aws lambda) that just re-sends the data a mobile carrier's sms gateway which would make a phone alert whenever there's a reminder event.  There's nothing both free+private that does that!

**Comment by ben-spiller** [comment]
Hi thanks for getting in touch, glad you're finding it useful!

It's an interesting idea but I'm not gonna take that into this project, there are quite a few details and edge cases one would need to consider. I think it would be better for that functionality to live in a separate addin. However this code is opensource (MIT-licensed) so feel free to take a fork and use it as the starting point for an adding that does REST calls if you'd find it helpful
